apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparglim-app
  namespace: sparglim
  labels:
    app: sparglim
spec:
  replicas: 1

  selector:
    matchLabels:
      app: sparglim-app
  template:
    metadata:
      labels:
        app: sparglim-app
    spec:
      containers:
        - name: sparglim-app
          image: wh1isper/jupyterlab-sparglim
          ports:
            - containerPort: 8888
          imagePullPolicy: Always
          env:
            - name: SPARGLIM_SQL_MODE
              value: connect_client
            - name: SPARGLIM_REMOTE
              value: "sc://sparglim-server-headless-service:15002"
            - name: SPARGLIM_DRIVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARGLIM_DRIVER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
