apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparglim-server
  namespace: sparglim
  labels:
    app: sparglim-server
spec:
  replicas: 1

  selector:
    matchLabels:
      app: sparglim-server
  template:
    metadata:
      labels:
        app: sparglim-server
    spec:
      containers:
        - name: sparglim-server
          image: wh1isper/sparglim-server:dev
          ports:
            - containerPort: 15002
          imagePullPolicy: Never
          env:
            - name: SPARGLIM_SERVER_MODE
              value: "k8s"
            - name: SPARGLIM_DRIVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARGLIM_DRIVER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
