FROM wh1isper/spark-connector-server:3.4.1

RUN pip install sparglim

ENTRYPOINT [ "tini" ,"--"]
CMD [ "sparglim-server", "start" ]

# docker buildx build --platform linux/amd64,linux/arm64/v8 -t wh1isper/sparglim-server:latest -f docker/Dockerfile.sparglim-server --push .
