FROM python:3.10.12-slim-bookworm as builder

RUN pip install build twine hatch
COPY . /source
WORKDIR /source
RUN python -m build

FROM wh1isper/spark-connector-server:3.4.1

COPY --from=builder /source/dist/*.whl /tmp/
RUN pip install --no-cache-dir $(echo /tmp/*.whl)

ENTRYPOINT [ "tini" ,"--"]
CMD [ "sparglim-server", "start" ]

# docker buildx build --platform linux/amd64,linux/arm64/v8 -t wh1isper/sparglim-server:latest -f docker/Dockerfile.sparglim-server --push .
