name: Build Docker Image manually

on:
    workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Build docker images
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push jupyterlab-sparglim
      id: docker_build_jupyterlab_sparglim
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile.jupyterlab-sparglim
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab-sparglim:${{  github.ref_name }}
    -
      name: Build and push sparglim-server
      id: docker_build_sparglim_server
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile.sparglim-server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sparglim-server:${{  github.ref_name }}

    -
      name: Build and push jupyterlab-sparglim_latest
      id: docker_build_jupyterlab_sparglim_latest
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile.jupyterlab-sparglim
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab-sparglim:latest
    -
      name: Build and push sparglim-server_latest
      id: docker_build_sparglim_server_latest
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile.sparglim-server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sparglim-server:latest
