name: Release docker image

on:
  workflow_dispatch: {}
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Self versioning
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine hatch
      - name: Versioning package
        run: hatch version ${{ github.ref_name }}
      # Publish
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push tagged jupyterlab-sparglim image
        id: docker_build_jupyterlab_sparglim
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          file: ./docker/Dockerfile.jupyterlab-sparglim
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab-sparglim:${{ github.ref_name }}
      -
        name: Build and push tagged sparglim-server image
        id: docker_build_sparglim_server
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          file: ./docker/Dockerfile.sparglim-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sparglim-server:${{ github.ref_name }}
