name: Push docker image

on:
    release:
      types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build_jupyterlab_sparglim
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.jupyterlab-sparglim
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab-sparglim:$GITHUB_REF_NAME
      -
        name: Build and push
        id: docker_build_sparglim_server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.sparglim-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sparglim-server:$GITHUB_REF_NAME
