FROM wh1isper/spark-connector-server:3.4.1

COPY --chown=executor:executor ./ ./sparglim
RUN pip install --no-cache-dir ./sparglim

ENTRYPOINT [ "tini" ,"--"]
CMD [ "sparglim-server", "start" ]

# docker build -t wh1isper/sparglim-server:dev -f dev/docker/Dockerfile.sparglim-server . && ./dev/scripts/reload.sh
